TessellDevelopment/convoy-ci

- .github/workflows/build_terraform_modules.yml
> Changes to push to nexus

- .github/workflows/build_infra_provision_worker.yml
> Changes to download openapi generator

- .github/workflows/create_double_commit.yml
> Added additional command to run on cherry pick failure

- .github/workflows/build_terraform_modules.yml
build changes related to versioning 
> TS-9406_build

- .github/workflows/build_go_docker_image.yml
- .github/workflows/build_infra_provision_worker.yml
> Continue on failure for image scan until

- .github/workflows/build_python_docker_image.yml
> Ts 10400 2

- .github/workflows/build_db_plugins.yml
- .github/workflows/build_devops.yml
- .github/workflows/build_python_library.yml
- .github/workflows/build_vault_client_library.yml
- .github/workflows/build_vault_configurator.yml
> TS-10671: Update pip install to dry-run in build

- .github/workflows/build_pipeline.yml
- .github/workflows/create-new-repository.yml
- .github/workflows/create-release-branch.yml
- .github/workflows/dev-checks.yml
- .github/workflows/git-repository-settings-check.yml
- .github/workflows/tessell-release-build-pipeline.yml
- github-actions/create-release-branch/action.yml
- github-actions/create-release-branch/index.js
- github-actions/dispatch-build-and-wait/action.yml
- github-actions/dispatch-build-and-wait/index.js
> Changes to include TDEVOPS-

- .github/workflows/build_devops.yml
> Push images for devops service

- .github/workflows/create_double_commit.yml
> TDEVOPS-305: DC is trying to create even for DC PR

- .github/workflows/dev-checks.yml
> TDEVOPS-476 | Merge Conflict Resolved

- .github/workflows/dev-checks.yml
> TDEVOPS-508 | Check to skip unreadable files while checking for merge conflict

- .github/workflows/dev-checks.yml
> TDEVOPS-399 | Terraform version check in convoy-config

- .github/workflows/build_terraform_modules.yml
> Fix the build failure for terraform module

- .github/workflows/auto_merge.yml
- .github/workflows/dev-checks.yml
> TDEVOPS-539 | double commit check

- .github/workflows/dev-checks.yml
> double check bug

- .github/workflows/dev-checks.yml
> TDEVOPS-629

- .github/workflows/dev-checks.yml
> TDEVOPS-574 | Validate Version in nexus

- .github/workflows/create_double_commit.yml
> TDEVOPS | double quotes to single quote for conflicts in PR title

- .github/workflows/create_double_commit.yml
- .github/workflows/dev-checks.yml
> TDEVOPS-667 | Quotes and Revert fix

- .github/workflows/create_tag.yml
> TDEVOPS-597 | POST API tag output

- .github/workflows/dev-checks.yml
> Updated dev checks

- .github/workflows/create_tag.yml
> TDEVOPS-781 | Updated the commit message variable

- .github/workflows/build_qa.yml
> TS-14595 | CI changes to upload QA dockerImage in case of Dockerfile change

- .github/workflows/dev-checks.yml
> TDEVOPS-841 | Conditional for version check

- .github/workflows/build_db_plugins.yml
- .github/workflows/build_devops.yml
- .github/workflows/build_elastic.yml
- .github/workflows/build_functions.yml
- .github/workflows/build_go_docker_image.yml
- .github/workflows/build_go_library.yaml
- .github/workflows/build_infra_provision_worker.yml
- .github/workflows/build_java_docker_image.yml
- .github/workflows/build_java_library.yml
- .github/workflows/build_pipeline.yml
- .github/workflows/build_pushprox.yml
- .github/workflows/build_python_docker_image.yml
- .github/workflows/build_python_library.yml
- .github/workflows/build_qa.yml
- .github/workflows/build_terraform_modules.yml
- .github/workflows/build_tessell_openapi_java_generator.yml
- .github/workflows/build_tsm_infra.yml
- .github/workflows/build_ui.yml
- .github/workflows/build_workflows.yml
> TDEVOPS-774-2 | Added Build POST API to all build files

- .github/workflows/build_agent.yml
- .github/workflows/build_db_plugins.yml
- .github/workflows/build_elastic.yml
- .github/workflows/build_functions.yml
- .github/workflows/build_go_library.yaml
- .github/workflows/build_pushprox.yml
- .github/workflows/build_qa.yml
- .github/workflows/build_terraform_modules.yml
> TDEVOPS-781 | Upload artifacts to S3 buckets

- .github/workflows/build_devops.yml
- .github/workflows/build_functions.yml
- .github/workflows/build_python_library.yml
> TDEVOPS-774 | Updated EOF bug

- .github/workflows/build_agent.yml
- .github/workflows/build_db_plugins.yml
- .github/workflows/build_elastic.yml
- .github/workflows/build_functions.yml
- .github/workflows/build_go_library.yaml
- .github/workflows/build_pushprox.yml
> TDEVOPS-781 | S3 updated path

- .github/workflows/build_db_plugins.yml
> TDEVOPS-781 | S3 path change

- .github/workflows/build_tsm_infra.yml
> TDEVOPS-597 | Version file change in tsm infra

- .github/workflows/create_tag.yml
> TDEVOPS-781 | Commit message in POST API

- .github/workflows/build_pushprox.yml
> TDEVOPS-860 | Docker tag changes

- .github/workflows/build_terraform_modules.yml
> TDEVOPS-597 | Tf modules version file change

- .github/workflows/dev-checks.yml
> Nexus version py-component bug

- .github/workflows/dev-checks.yml
> TDEVOPS-902 | Top level convoy.yaml exclude in tf-modules

- .github/workflows/build_terraform_modules.yml
- .github/workflows/dev-checks.yml
> TDEVOPS-902 | Build exclude

- .github/workflows/dev-checks.yml
> TDEVOPS-902 | Check version for tf-modules

- .github/workflows/build_frp.yml
> TDEVOPS-766 | FRP CI 

- .github/workflows/create_tag.yml
> TDEVOPS-971 | tf-folder path bug fix

- .github/workflows/build_terraform_modules.yml
> TDEVOPS-781 | Upload tf modules with version to s3

- .github/workflows/build_go_library.yaml
> TS-15971 | Reversed config for exporter to handle duplicates in dictionary

- .github/workflows/build_agent.yml
- .github/workflows/build_db_plugins.yml
- .github/workflows/build_devops.yml
- .github/workflows/build_elastic.yml
- .github/workflows/build_functions.yml
- .github/workflows/build_go_docker_image.yml
- .github/workflows/build_go_library.yaml
- .github/workflows/build_infra_provision_worker.yml
- .github/workflows/build_java_docker_image.yml
- .github/workflows/build_java_library.yml
- .github/workflows/build_npm.yml
- .github/workflows/build_pipeline.yml
- .github/workflows/build_pushprox.yml
- .github/workflows/build_python_docker_image.yml
- .github/workflows/build_python_library.yml
- .github/workflows/build_qa.yml
- .github/workflows/build_terraform_modules.yml
- .github/workflows/build_tessell_openapi_java_generator.yml
- .github/workflows/build_tsm_infra.yml
- .github/workflows/build_ui.yml
- .github/workflows/build_workflows.yml
- .github/workflows/create_tag.yml
> TDEVOPS-920 | Convoy API Slack notif

- .github/workflows/build_agent.yml
- .github/workflows/build_db_plugins.yml
- .github/workflows/build_elastic.yml
- .github/workflows/build_functions.yml
- .github/workflows/build_go_library.yaml
- .github/workflows/build_pushprox.yml
> TS-16463 | Changed s3 path

- .github/workflows/build_devops.yml
- .github/workflows/build_elastic.yml
- .github/workflows/build_go_docker_image.yml
- .github/workflows/build_infra_provision_worker.yml
- .github/workflows/build_java_docker_image.yml
- .github/workflows/build_pushprox.yml
- .github/workflows/build_python_docker_image.yml
> TDEVOPS-1033 | No image scan post merge

- .github/workflows/build_agent.yml
- .github/workflows/build_db_plugins.yml
- .github/workflows/build_elastic.yml
- .github/workflows/build_functions.yml
- .github/workflows/build_go_library.yaml
- .github/workflows/build_pushprox.yml
- .github/workflows/build_terraform_modules.yml
> TDEVOPS-781 | Changed s3 file name

- .github/workflows/dev-checks.yml
> TDEVOPS-1088 | Formatting bug

- .github/workflows/build_go_library.yaml
> TDEVOPS-1061 | Victoria-metrics CI Changes

- .github/workflows/build_go_library.yaml
> TDEVOPS-957 | Db-perf-exporter changes

- .github/workflows/build_image_milvus.yml
> TDEVOPS-1111 | Added no cache in milvus

- .github/workflows/create_tag.yml
> TDEVOPS-1008 | POST API Payload changes

- .github/workflows/build_opa_policies.yml
> TDEVOPS-1125 | OPA CI changes

- .github/workflows/dev-checks.yml
> TDEVOPS-1167 | Changed key for jira validation

- .github/workflows/build_frp.yml
- .github/workflows/master_cherry_pick.yml
> TDEVOPS-766 | Cherry Pick workflow for frp

- .github/workflows/build_frp.yml
> TDEVOPS-1075 | Added Dockerimage and tag support for FRP

- .github/workflows/build_ui.yml
> TDEVOPS-1132 | UI build changes for common-ui

- .github/workflows/dev-checks.yml
> TDEVOPS-1132 | Added Common-ui config in dev-check for npm install

- .github/workflows/build_image_milvus.yml
- .github/workflows/create_tag.yml
- .github/workflows/dev-checks.yml
> TDEVOPS-1167 | Handle updated convoy changes

- .github/workflows/dev-checks.yml
> TDEVOPS-1091 | Added SRE in format check

- .github/workflows/build_infra_provision_worker.yml
> TDEVOPS-1207 | Added raw artifacts

- .github/workflows/build_helm_svc_defns.yml
- .github/workflows/dev-checks.yml
> TDEVOPS-41 | Helm-svc-defns CI

- .github/workflows/build_elastic.yml
> TS-17655 | Added filebeat.service in tar

- .github/workflows/create_tag.yml
> TDEVOPS-1167 | Increased file limit in git API

- .github/workflows/create_tag.yml
- .github/workflows/master_approve.yml
- .github/workflows/master_auto_merge.yml
- .github/workflows/master_build_dispatch.yml
- .github/workflows/master_build_merge.yml
- .github/workflows/master_build_pr.yml
- .github/workflows/master_check_approval.yml
- .github/workflows/master_check_version.yml
- .github/workflows/master_create_double_commit.yml
- .github/workflows/master_create_tag.yml
- .github/workflows/master_dev_checks.yml
- .github/workflows/master_file_check.yml
- .github/workflows/master_find_latest_tag.yml
- .github/workflows/master_merge.yml
- .github/workflows/master_post_build_convoy.yml
- .github/workflows/master_post_message.yml
- .github/workflows/master_post_tag_convoy.yml
- .github/workflows/master_pr.yml
- .github/workflows/master_read_codeowners.yml
- .github/workflows/master_send_email.yml
> TDEVOPS-827 | Master CI

- .github/workflows/master_approve.yml
- .github/workflows/master_build_dispatch.yml
- .github/workflows/master_merge.yml
- .github/workflows/master_pr.yml
> TDEVOPS-827 | Changed ref to main

- .github/workflows/build_qa.yml
> TDEVOPS-867| Fix dev-check failure due to incorrect harness-library version overwriting

- .github/workflows/build_devops.yml
- .github/workflows/build_elastic.yml
- .github/workflows/build_go_docker_image.yml
- .github/workflows/build_infra_provision_worker.yml
- .github/workflows/build_java_docker_image.yml
- .github/workflows/build_pushprox.yml
- .github/workflows/build_python_docker_image.yml
> TDEVOPS-1282 | update dct tag from latest to hash

- .github/workflows/build_qa.yml
> TDEVOPS-1300 | Build failure in QA as virtual env was not set

- .github/workflows/build_frp.yml
> TDEVOPS-1309 | Reading dockerfile from convoy.yaml

- .github/workflows/build_go_library.yaml
> TDEVOPS-1262 | Updated go version and build logic in build_go_library

- .github/workflows/master_patch_service_manifest.yaml
> TDEVOPS-1244 | Added patch call for service manifest

- .github/workflows/build_go_library.yaml
> TDEVOPS-1329 | Add slack notification and mail in builld_go_library

- .github/workflows/create_tag.yml
- .github/workflows/master_patch_service_manifest.yaml
> TDEVOPS-1250 | Passing all folders for tf modules POST-API

- .github/workflows/build_helm_svc_defns.yml
- .github/workflows/create_tag.yml
> TDEVOPS-1250 | Using custom version as tag

- .github/workflows/create_tag.yml
> TDEVOPS-1250 | Changed npm install command

- .github/workflows/create_tag.yml
- .github/workflows/master_create_tag.yml
- .github/workflows/master_merge.yml
- .github/workflows/master_post_tag_convoy.yml
> TDEVOPS-1250 | POST API update in Master_CI

- .github/workflows/create_tag.yml
> TDEVOPS-1250 | Removed custom_version as tag for non-helm repos

- .github/workflows/packer_workflow_dispatch.yml
> TDEVOPS-1366-cloudType | added cloudType

- .github/workflows/build_npm.yml
- .github/workflows/build_ui.yml
- .github/workflows/create_tag.yml
- .github/workflows/dev-checks.yml
- .github/workflows/master_create_tag.yml
- .github/workflows/master_dev_checks.yml
> TDEVOPS-1132 | Added common-ui config in create-tag

- .github/workflows/master_build_merge.yml
- .github/workflows/master_build_pr.yml
- .github/workflows/master_check_version.yml
- .github/workflows/master_create_tag.yml
- .github/workflows/master_dev_checks.yml
- .github/workflows/master_pr.yml
> TDEVOPS-1382 | Removed npm dependency and build fail safe

- .github/workflows/dev-checks.yml
- .github/workflows/master_dev_checks.yml
> TDEVOPS-1361 | Added api-spec validation check

- .github/workflows/build_agent.yml
- .github/workflows/build_db_plugins.yml
- .github/workflows/build_devops.yml
- .github/workflows/build_elastic.yml
- .github/workflows/build_frp.yml
- .github/workflows/build_functions.yml
- .github/workflows/build_go_docker_image.yml
- .github/workflows/build_go_library.yaml
- .github/workflows/build_helm_svc_defns.yml
- .github/workflows/build_image_milvus.yml
- .github/workflows/build_image_milvus_arm.yml
- .github/workflows/build_infra_provision_worker.yml
- .github/workflows/build_java_docker_image.yml
- .github/workflows/build_java_library.yml
- .github/workflows/build_npm.yml
- .github/workflows/build_opa_policies.yml
- .github/workflows/build_pipeline.yml
- .github/workflows/build_pushprox.yml
- .github/workflows/build_python_docker_image.yml
- .github/workflows/build_python_library.yml
- .github/workflows/build_qa.yml
- .github/workflows/build_terraform_modules.yml
- .github/workflows/build_tessell_openapi_java_generator.yml
- .github/workflows/build_tsm_infra.yml
- .github/workflows/build_ui.yml
- .github/workflows/build_workflows.yml
- .github/workflows/convoy-build-docker-workflows.yaml
- .github/workflows/master_post_build_convoy.yml
> TDEVOPS-1430 | Increased retry_delay for POST build

- .github/workflows/master_approve.yml
> TDEVOPS-1427 | Handled update_branch in check approval

- .github/workflows/build_db_plugins.yml
> TDEVOPS-1470 | Fixed extension in db_plugin path

- .github/workflows/build_governance_worker.yml
> TDEVOPS-689 | Changes in docker image scan for governance-worker

- .github/workflows/build_frp.yml
- .github/workflows/build_image_milvus.yml
- .github/workflows/build_image_milvus_arm.yml
> TDEVOPS-1412 | Added multi-platform build for milvus

- .github/workflows/build_image_milvus_arm.yml
> TDEVOPS-1412 | Removed docker image scan for milvus plugin Image

- .github/workflows/build_infra_provision_worker.yml
> TDEVOPS-1527 | Set GITHUB_TOKEN for infra-provision-worker build

- .github/workflows/build_infra_provision_worker.yml
> TDEVOPS-1520 | Corrected variable in infra build

- .github/workflows/create_tag.yml
> TDEVOPS-1491 | Added committedAt in create-tag Payload

- .github/workflows/build_devops.yml
> TDEVOPS-1556 | Add java 17 for ubuntu-latest runner

- .github/workflows/build_elastic.yml
- .github/workflows/build_infra_provision_worker.yml
> TDEVOPS-1556 | Added setup JDK17 for ubuntu latest

- .github/workflows/build_infra_provision_worker.yml
- .github/workflows/build_opa_policies.yml
- .github/workflows/convoy-build-docker-workflows.yaml
- .github/workflows/create_tag.yml
- .github/workflows/master_create_tag.yml
- .github/workflows/master_merge.yml
- .github/workflows/master_patch_service_manifest.yaml
> TDEVOPS-1554 | Added seprate NEXUS and GITHUB tokens for internal build and changed to api-key

- .github/workflows/dev-checks.yml
- .github/workflows/master_dev_checks.yml
> TDEVOPS-1381 | Added YAML and .tmpl Validation

- .github/workflows/build_ui.yml
> TDEVOPS-1557 | Added .env in UI build

- .github/workflows/build_packer_config.yml
- .github/workflows/replicate_regions_workflow_dispatch.yml
> TDEVOPS-1459 | started adding workflow dispatch for region replication

- .github/workflows/dev-checks.yml
- .github/workflows/master_dev_checks.yml
> TDEVOPS-1381 | Reverting YAML and .tmpl validator

- .github/workflows/master_post_tag_convoy.yml
> TDEVOPS-1491 | Added committedAt in master-ci

- .github/workflows/build_ui.yml
> TDEVOPS-1518 | Switching to different runner for UI

- .github/workflows/build_ui.yml
> TDEVOPS-1596 | Add fetch depth

- .github/workflows/build_agent.yml
- .github/workflows/build_functions.yml
- .github/workflows/build_image_milvus_arm.yml
> TDEVOPS-1566 | Segregate Variables in Makefiles

- .github/workflows/build_agent.yml
- .github/workflows/build_functions.yml
- .github/workflows/build_helm_svc_defns.yml
> TDEVOPS-1587 | Fix nexus variable name

- .github/workflows/build_devops.yml
> TDEVOPS-1569 | devops build fix

- .github/workflows/build_db_plugins.yml
- .github/workflows/build_devops.yml
- .github/workflows/build_governance_worker.yml
- .github/workflows/build_infra_provision_worker.yml
- .github/workflows/build_python_docker_image.yml
- .github/workflows/build_python_library.yml
- .github/workflows/build_qa.yml
- .github/workflows/packer_workflow_dispatch.yml
- .github/workflows/replicate_regions_workflow_dispatch.yml
> TDEVOPS-1554 | Added trusted host in pip install

- .github/workflows/replicate_regions_workflow_dispatch.yml
> TDEVOPS-1626 | Typo fix in nexus url and added env PATH

- .github/workflows/build_python_docker_image.yml
> TDEVOPS-1675 | Update build_python_docker_image.yml

- .github/workflows/master_build_pr.yml
- .github/workflows/master_pr.yml
> TDEVOPS-1672 | Send repo and image name in slack in vuln scan

- .github/workflows/build_python_docker_image.yml
Reverts TessellDevelopment/convoy-ci#262
> Revert "TDEVOPS-1757 | Changed to git credentials for monitoring-infra-worker build failure"

- .github/workflows/build_python_docker_image.yml
- .github/workflows/build_qa.yml
> TDEVOPS-1747 | Resolving QA build

- .github/workflows/build_qa.yml
> TDEVOPS-1747 | Changing config for QA build

- .github/workflows/master_approve.yml
- .github/workflows/master_pr.yml
> TDEVOPS-1779 | Master-CI Improvements

- .github/workflows/master_build_merge.yml
> TDEVOPS-1382 | Added mvnDeploy for jar build

- .github/workflows/master_build_merge.yml
> TDEVOPS-1382 | Updated nexus path

- .github/workflows/master_build_merge.yml
> TDEVOPS-1846 | Added missing function

- .github/workflows/master_build_merge.yml
- .github/workflows/master_post_tag_convoy.yml
> TDEVOPS-1846 | POST Tag improvement

- .github/workflows/master_build_merge.yml
> TDEVOPS-1874 | dockerBuild bug in Merge function

- .github/workflows/master_dev_checks.yml
- .github/workflows/master_pr.yml
> TDEVOPS-1824 | Resolving Argument list too long

- .github/workflows/master_check_approval.yml
- .github/workflows/master_post_message.yml
- .github/workflows/master_pr.yml
> TDEVOPS-1891 | Increased response limit in git api calls

- .github/workflows/build_frp.yml
> TS-18733 | Fixing FRP build

- .github/workflows/build_frp.yml
> TDEVOPS-1923 | FRP variable fix

- .github/workflows/packer_workflow_dispatch.yml
> TDEVOPS-1935 | Fix AWS plugin installation in workflow-dispatch

- .github/workflows/convoy-build-docker-workflows.yaml
> TDEVOPS-1950 | Skip running docker scan post merge

- .github/workflows/master_build_merge.yml
- .github/workflows/master_build_pr.yml
> TDEVOPS-1848 | Updated path for ops-ui artifact push

- .github/workflows/master_build_merge.yml
- .github/workflows/master_build_pr.yml
> TDEVOPS-1953 | Changed variable name

- .github/workflows/master_approve.yml
- .github/workflows/master_build_merge.yml
> TDEVOPS-1955 | Handling null case and OPS UI update

- .github/workflows/packer_workflow_dispatch.yml
> TDEVOPS-1978 | Add tags for packer workflow dispatch

- .github/workflows/master_build_merge.yml
- .github/workflows/master_build_pr.yml
> TDEVOPS-2016 | Adds github args to dockerBuild

- .github/workflows/master_build_merge.yml
- .github/workflows/master_build_pr.yml
- .github/workflows/master_pr.yml
> TDEVOPS-2036 | Changes otelcol to use makefile

- .github/workflows/master_build_pr.yml
- .github/workflows/master_pr.yml
> Tdevops 2028

- .github/workflows/master_build_pr.yml
- .github/workflows/master_pr.yml
> TDEVOPS-2028 | Enable unit test running for infra-provision-worker

- .github/workflows/master_build_merge.yml
- .github/workflows/master_build_pr.yml
- .github/workflows/master_pr.yml
> TDEVOPS-2102 | Build functions for python api clients

- .github/workflows/build_packer_config.yml
- .github/workflows/create_tag.yml
- .github/workflows/packer_workflow_dispatch.yml
> TDEVOPS-1694

- .github/workflows/packer_workflow_dispatch.yml
> TDEVOPS-1694 | Fix installation for packer workflow dispatch

- .github/workflows/build_packer_config.yml
> TDEVOPS-1694 | Fix installation for packer-config requirement.txt

- .github/workflows/master_build_pr.yml
- .github/workflows/master_pr.yml
> TDEVOPS-2244 | Run packagePlugin task for plugin repositories

- .github/workflows/build_frp.yml
> TDEVOPS-2298 | Remove copy of settings.xml for frps repository

- .github/workflows/master_build_merge.yml
- .github/workflows/master_build_pr.yml
> TDEVOPS-2298 | Remove copy of settings.xml for self-hosted runners

- .github/workflows/build_packer_config.yml
- .github/workflows/packer_workflow_dispatch.yml
> TS-22121 | Move packer installation process to ci-runner base image

- .github/workflows/master_build_merge.yml
- .github/workflows/master_build_pr.yml
> TDEVOPS-1125 | Create bundles folder for opa artifact

- .github/workflows/master_build_merge.yml
> TDEVOPS-1382 | Change build command for ops jar build

- .github/workflows/master_build_merge.yml
> TDEVOPS-2353 | Fix docker login

- .github/workflows/master_build_pr.yml
> TDEVOPS-2285 | Update new vulnerabilities Endpoint

- .github/workflows/master_build_pr.yml
> TDEVOPS-2285 | Update new vulnerabilities Endpoint (race-condition)

- .github/workflows/master_build_merge.yml
> TDEVOPS-2380 | Add alt deployment repository override in mvn deploy

- .github/workflows/master_build_merge.yml
> TDEVOPS-1377 | Add checksum for amd-go-21

- .github/workflows/master_dev_checks.yml
- .github/workflows/master_pr.yml
> TDEVOPS-2402 | Add trivy filesystem scan as devcheck

- .github/workflows/master_build_merge.yml
- .github/workflows/master_build_pr.yml
- .github/workflows/master_pr.yml
> TDEVOPS-1326 | Add Master CI code for tailscale repo

- .github/workflows/master_build_merge.yml
- .github/workflows/master_build_pr.yml
- .github/workflows/master_pr.yml
> TDEVOPS-2412 | Fail when function not found

- .github/workflows/master_build_merge.yml
- .github/workflows/master_build_pr.yml
- .github/workflows/master_pr.yml
> TDEVOPS-1992 | Add functions for pythonDockerBuild

- .github/ci-scripts/bash/functions-for-build
- .github/ci-scripts/bash/functions-for-build-camel-case
- .github/workflows/master_build_merge.yml
> TDEVOPS-1992 | Move the functions to scripts

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-1992 | Fix env variable error

- .github/ci-scripts/bash/functions-for-build
- .github/ci-scripts/bash/functions-for-build-camel-case
- .github/workflows/master_build_pr.yml
- .github/workflows/master_pr.yml
> TDEVOPS-2413 | Functions for convoy-tessell

- .github/workflows/master_post_build_convoy.yml
> TDEVOPS-2424 | POST Build API fix for repos with no artifacts

- .github/workflows/master_build_merge.yml
- .github/workflows/master_build_pr.yml
Reverts TessellDevelopment/convoy-ci#322
> Revert "TDEVOPS-2412 | Fail when function not found"

- .github/ci-scripts/bash/functions-for-build
- .github/workflows/master_build_merge.yml
> TDEVOPS-2284 | Generate report only when running unit test

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-2482 | Fix syntax

- .github/workflows/master_build_merge.yml
- .github/workflows/master_build_pr.yml
> TDEVOPS-2452 | Subscription readiness functionBuild fix

- .github/workflows/master_build_merge.yml
- .github/workflows/master_build_pr.yml
> TDEVOPS-2540 | Add support for go-22 in CI

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-2576 | Fix goimports version

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-2573 | Fix build-push fail in codegen

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-2482 | Bug fix

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-2482 | Code lost due to merge conflicts

- .github/ci-scripts/bash/functions-for-build
- .github/ci-scripts/bash/functions-for-build-camel-case
- .github/workflows/master_build_pr.yml
- .github/workflows/master_pr.yml
> TDEVOPS-1828 | CI Function for convoy-gradle-plugins

- .github/ci-scripts/bash/functions-for-build
- .github/ci-scripts/bash/functions-for-build-camel-case
- .github/workflows/master_build_merge.yml
- .github/workflows/master_build_pr.yml
> TDEVOPS-2625 | Fix mvn deploy command with'nexus::default::'

- .github/ci-scripts/bash/functions-for-build
- .github/ci-scripts/bash/functions-for-build-camel-case
- .github/workflows/master_build_merge.yml
- .github/workflows/master_build_pr.yml
> TS-23106 | Move elasticAgentBuild to build script

- .github/ci-scripts/bash/functions-for-build
- .github/workflows/master_build_dispatch.yml
- .github/workflows/master_build_merge.yml
- .github/workflows/master_find_latest_tag.yml
> TDEVOPS-433 | Workflow dispatch changes for dev builds

- .github/workflows/master_build_dispatch.yml
> TDEVOPS-433 | Fix branch name

- .github/ci-scripts/bash/functions-for-build
- .github/workflows/master_build_merge.yml
> TDEVOPS-433 | Fix conditional

- .github/workflows/master_build_merge.yml
> TDEVOPS-433 | Fix helm chart conditional

- .github/workflows/master_build_merge.yml
> TDEVOPS-433 | Add force push for helm dev dispatch

- .github/workflows/build_packer_config.yml
> TDEVOPS-2650 | Fix validation step in build_packer_config

- .github/workflows/master_merge.yml
> TDEVOPS-2663 | Create DC post build completion

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-2568 | Fix nexus secrets

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-2568 | Fix for getting root pr message from dc PR

- .github/workflows/packer_workflow_dispatch.yml
> TDEVOPS-2705 | upload the delta-image-manifest generated in workflow dispatch

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-2627 | Add set -e in software_def_build function to exit on error

- .github/workflows/master_merge.yml
> TDEVOPS-2708 | Handle DC creation in case of no build

- .github/workflows/master_build_merge.yml
> TDEVOPS-2732 | Fix tailscale acl command

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-2709 | Increase retries and timeout for trivy scan

- .github/workflows/packer_workflow_dispatch.yml
changes:
SOURCE_BRANCH is renamed to PR_SOURCE_BRANCH (update: reverted)
BRANCH_NAME is renamed to BASE_BRANCH
TARGET_BRANCH is removed (was not getting used anywhere)
Code cleanup
> TDEVOPS-2808: code cleanup of packer workflow dispatch

- .github/workflows/master_post_build_convoy.yml
> TDEVOPS-2825 | Make path app group specific

- .github/workflows/master_pr.yml
> TDEVOPS-2708 | Auto merge in case of no build

- .github/workflows/packer_workflow_dispatch.yml
> TDEVOPS-2723 | Add DEVELOPMENT tags for workflow-dispatch created artifacts

- .github/workflows/master_build_merge.yml
> TDEVOPS-2880 | Reverted python38 in masteR_build_merge

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-2824 | Add checksum for ops build

- .github/workflows/master_build_merge.yml
> TDEVOPS-2851 | Fix app group name to use from variable

- .github/ci-scripts/bash/functions-for-build
- .github/workflows/master_approve.yml
- .github/workflows/master_pr.yml
> TDEVOPS-2917 | Fix false positive in check-commits failure

- .github/workflows/master_check_approval.yml
> TDEVOPS-2923 | Increase team member list

- .github/workflows/master_build_merge.yml
- .github/workflows/master_merge.yml
> TDEVOPS-2851 | Move gcloud docker build code to build-amd

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-2940 | Handle checksum in ops builds

- .github/workflows/master_post_build_convoy.yml
> TDEVOPS-2940 | Check for excluded artifacts with checksum

- .github/workflows/master_build_merge.yml
> TDEVOPS-2901 | Push all terraform modules for workflow dispatch

- .github/workflows/master_build_merge.yml
> TDEVOPS-2901 | Handle dir name for dispatch

- .github/workflows/master_build_merge.yml
> TDEVOPS-2901 | Fix failure due to build folder

- .github/ci-scripts/bash/functions-for-build
- .github/workflows/master_build_dispatch.yml
- .github/workflows/master_build_merge.yml
- .github/workflows/master_merge.yml
- .github/workflows/master_sonar_scan.yml
> TDEVOPS-3001 | Run sonar-scanner on merge

- .github/ci-scripts/bash/functions-for-build
- .github/workflows/master_build_merge.yml
> TDEVOPS-3032 | Stop pushing to tesselltools/terls

- .github/workflows/master_dev_checks.yml
- .github/workflows/master_pr.yml
> TDEVOPS-2967 | Add support for 'enableNewLineAtEOF' in convoy.yaml

- .github/workflows/master_post_build_convoy.yml
> TDEVOPS-3036 | Fix dot notation if extension is empty

- .github/workflows/master_find_latest_tag.yml
> TDEVOPS-3042 | Fix find latest tag in case of helm versions

- .github/workflows/master_create_tag.yml
- .github/workflows/master_find_latest_tag.yml
> TDEVOPS-3042 | Change git command to get tags related to a commit

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-3090 | Exclude ci-scripts from sonar-scan

- .github/workflows/packer_workflow_dispatch.yml
> TDEVOPS-3150 | Fix push to minio in swim wf dispatch

- .github/workflows/packer_workflow_dispatch.yml
> TDEVOPS-3186 | Pull sm from minio instead of nexus for workflow-dispatch

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-3284 | Push tf-modules to tesselltools under release path

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-3284 | Stop pushing to tessell-terraform-modules-*

- .github/workflows/packer_workflow_dispatch.yml
> TDEVOPS-3327 | Tag swim with branch name rather than jira number

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-2568 | Fix getting root pr tag for software-manifest DC PR

- .github/ci-scripts/bash/functions-for-build
Reverts TessellDevelopment/convoy-ci#464
> Revert "TDEVOPS-3284 | Stop pushing to tessell-terraform-modules-*"

- .github/workflows/packer_workflow_dispatch.yml
> TDEVOPS-2817 | Fix packer_workflow_dispatch.yml upload nexus-path

- .github/workflows/packer_workflow_dispatch.yml
Reverts TessellDevelopment/convoy-ci#487
> Revert "TDEVOPS-2817 | Fix packer_workflow_dispatch.yml upload nexus-path"

- .github/workflows/master_dev_checks.yml
> TDEVOPS-1211 | Allow ubuntu-latest runner for go repos

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-3633 | Update API URL to `get_git_commit_info`

- .github/workflows/master_build_merge.yml
> TDEVOPS-3633 | Cleanup content-for-github-out after job is completed

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-3778 | Upload artifacts to convoy-minio based on `pushTO`

- .github/ci-scripts/bash/functions-for-artifacts-upload
- .github/workflows/master_build_merge.yml
> TDEVOPS-3759 | Add NEXUS_ADDR variable in all runner builds

- .github/ci-scripts/bash/functions-for-build
> TDEVOPS-3418 | Generate checksum for policy.hujson

- .github/workflows/master_build_merge.yml
Found that there are missing env in arm job, which failed the build for arm (s3 upload of code coverage data). Synced the env vars from the amd job to arm.
> TDEVOPS-3853 | Sync env: from amd job to arm job
